name: Check permissions

on:
  pull_request:
    paths:
      - '**/dependencies.gradle'

jobs:
  build-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: Build develop APK
        run: ./gradlew app:assembleDebug

      - name: Get permissions
        run: $ANDROID_HOME/build-tools/29.0.3/aapt d permissions app/build/outputs/apk/debug/app-debug.apk > permissions-develop.txt

      - name: Upload permissions file develop
        uses: actions/upload-artifact@v1
        with:
          name: permissions
          path: permissions-develop.txt
