name: Extract Develop Permissions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
  pull_request:
    types: [opened]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  build-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build develop APK
        run: ./gradlew app:assembleDebug
      - name: Get permissions
        run: $ANDROID_HOME/build-tools/33.0.1/aapt d permissions app/build/outputs/apk/debug/app-debug.apk > permissions-develop.txt

      - name: Upload permissions file develop
        uses: actions/upload-artifact@v1
        with:
         name: permissions
         path: permissions-develop.txt

  build-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build develop APK
        run: ./gradlew app:assembleDebug
      - name: Get permissions
        run: $ANDROID_HOME/build-tools/33.0.1/aapt d permissions app/build/outputs/apk/debug/app-debug.apk > permissions-branch.txt

      - name: Upload permissions file develop
        uses: actions/upload-artifact@v1
        with:
          name: permissions
          path: permissions-branch.txt

  diff-permissions:
    needs: [build-develop, build-branch]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Download permissions
        uses: actions/download-artifact@v1
        with:
          name: permissions

      - name: Execute diff
        run: diff --changed-group-format='%<%>' --unchanged-group-format='' $GITHUB_WORKSPACE/permissions/permissions-develop.txt $GITHUB_WORKSPACE/permissions/permissions-branch.txt > permissions-diff.txt && echo "NEW_PERMISSIONS=false" >> "$GITHUB_ENV" || echo "NEW_PERMISSIONS=false" >> "$GITHUB_ENV"

      - run: cat permissions-diff.txt
      - run: printf "⚠ New permission(s) found\n\n\`\`\`\n" > pr-comment.txt && cat permissions-diff.txt >> pr-comment.txt

      - name: add comment to PR
        if: env.NEW_PERMISSIONS == 'true'
        uses: mshick/add-pr-comment@v2
        with:
          message-path: pr-comment.txt
